version: "3.9"

services:
  flask-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development

